In [99]:
import pandas as pd
df=pd.read_csv(r"C:\Users\sumit\Desktop\Code\python\Machine Learning\Principle component\heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [100]:
df.shape

(918, 12)

In [101]:
df['zscr_bp']=(df.RestingBP-df.RestingBP.mean())/df.RestingBP.std()
df1=df[(df.zscr_bp<3) & (df.zscr_bp>-3)]
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscr_bp
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812

In [102]:
df1['zscr_ch']=(df1.Cholesterol-df1.Cholesterol.mean())/df1.Cholesterol.std()
df2=df1[(df1.zscr_ch<3) & (df1.zscr_ch>-3)]
df2.head()

C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\3593494925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['zscr_ch']=(df1.Cholesterol-df1.Cholesterol.mean())/df1.Cholesterol.std()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscr_bp,zscr_ch
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.823475
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.175198
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.768502
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.136315
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.037766

In [103]:
df2.shape

(907, 14)

In [104]:
df2['zscr_hr']=(df2.MaxHR-df2.MaxHR.mean())/df2.MaxHR.std()
df3=df2[(df2.zscr_hr<3) & (df2.zscr_hr>-3)]
df3.head()

C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\1489089356.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['zscr_hr']=(df2.MaxHR-df2.MaxHR.mean())/df2.MaxHR.std()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscr_bp,zscr_ch,zscr_hr
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.823475,1.385705
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.175198,0.755693
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.768502,-1.528100
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.136315,-1.134343
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.037766,-0.583082

In [105]:
df3['zscr_op']=(df3.Oldpeak-df3.Oldpeak.mean())/df3.Oldpeak.std()
df4=df3[(df3.zscr_op<3) & (df3.zscr_op>-3)]
df4.head()

C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\3986494821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['zscr_op']=(df3.Oldpeak-df3.Oldpeak.mean())/df3.Oldpeak.std()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscr_bp,zscr_ch,zscr_hr,zscr_op
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.823475,1.385705,-0.830801
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.175198,0.755693,0.108320
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.768502,-1.528100,-0.830801
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.136315,-1.134343,0.577881
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.037766,-0.583082,-0.830801

In [106]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df4.ChestPainType=le.fit_transform(df4.ChestPainType)
df4

C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\3123681668.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.ChestPainType=le.fit_transform(df4.ChestPainType)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscr_bp,zscr_ch,zscr_hr,zscr_op
0,40,M,1,140,289,0,Normal,172,N,0.0,Up,0,0.410685,0.823475,1.385705,-0.830801
1,49,F,2,160,180,0,Normal,156,N,1.0,Flat,1,1.490940,-0.175198,0.755693,0.108320
2,37,M,1,130,283,0,ST,98,N,0.0,Up,0,-0.129442,0.768502,-1.528100,-0.830801
3,48,F,0,138,214,0,Normal,108,Y,1.5,Flat,1,0.302660,0.136315,-1.134343,0.577881
4,54,M,2,150,195,0,Normal,122,N,0.0,Up,0,0.950812,-0.037766,-0.583082,-0.830801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,3,110,264,0,Normal,132,N,1.2,Flat,1,-1.209697,0.594422,-0.189325,0.296145
914,68,M,0,144,193,1,Normal,141,N,3.4,Flat,1,0.626736,-0.056090,0.165057,2.362211
915,57,M,0,130,131,0,Normal,115,Y,1.2,Flat,1,-0.129442,-0.624143,-0.858713,0.296145
916,57,F,1,130,236,0,LVH,174,N,0.0,Flat,1,-0.129442,0.337882,1.464457,-0.830801
917,38,M,2,138,175,0,Normal,173,N,0.0,Up,0,0.302660,-0.221009,1.425081,-0.830801

In [107]:
df4.Sex=le.fit_transform(df4.Sex)
df4.RestingECG=le.fit_transform(df4.RestingECG)
df4.ExerciseAngina=le.fit_transform(df4.ExerciseAngina)
df4.ST_Slope=le.fit_transform(df4.ST_Slope)
df4

C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\1855190341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.Sex=le.fit_transform(df4.Sex)
C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\1855190341.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.RestingECG=le.fit_transform(df4.RestingECG)
C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\1855190341.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.ExerciseAngina=le.fit_transform(df4.ExerciseAngina)
C:\Users\sumit\AppData\Local\Temp\ipykernel_5868\1855190341.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.ST_Slope=le.fit_transform(df4.ST_Slope)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscr_bp,zscr_ch,zscr_hr,zscr_op
0,40,1,1,140,289,0,1,172,0,0.0,2,0,0.410685,0.823475,1.385705,-0.830801
1,49,0,2,160,180,0,1,156,0,1.0,1,1,1.490940,-0.175198,0.755693,0.108320
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.129442,0.768502,-1.528100,-0.830801
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.302660,0.136315,-1.134343,0.577881
4,54,1,2,150,195,0,1,122,0,0.0,2,0,0.950812,-0.037766,-0.583082,-0.830801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,-1.209697,0.594422,-0.189325,0.296145
914,68,1,0,144,193,1,1,141,0,3.4,1,1,0.626736,-0.056090,0.165057,2.362211
915,57,1,0,130,131,0,1,115,1,1.2,1,1,-0.129442,-0.624143,-0.858713,0.296145
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.129442,0.337882,1.464457,-0.830801
917,38,1,2,138,175,0,1,173,0,0.0,2,0,0.302660,-0.221009,1.425081,-0.830801

In [108]:
y=df4.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 899, dtype: int64

In [109]:
df4

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscr_bp,zscr_ch,zscr_hr,zscr_op
0,40,1,1,140,289,0,1,172,0,0.0,2,0,0.410685,0.823475,1.385705,-0.830801
1,49,0,2,160,180,0,1,156,0,1.0,1,1,1.490940,-0.175198,0.755693,0.108320
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.129442,0.768502,-1.528100,-0.830801
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.302660,0.136315,-1.134343,0.577881
4,54,1,2,150,195,0,1,122,0,0.0,2,0,0.950812,-0.037766,-0.583082,-0.830801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,-1.209697,0.594422,-0.189325,0.296145
914,68,1,0,144,193,1,1,141,0,3.4,1,1,0.626736,-0.056090,0.165057,2.362211
915,57,1,0,130,131,0,1,115,1,1.2,1,1,-0.129442,-0.624143,-0.858713,0.296145
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.129442,0.337882,1.464457,-0.830801
917,38,1,2,138,175,0,1,173,0,0.0,2,0,0.302660,-0.221009,1.425081,-0.830801

In [110]:
x=df4.drop(['HeartDisease','zscr_bp','zscr_ch','zscr_hr','zscr_op'],axis='columns')
x

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,1,172,0,0.0,2
1,49,0,2,160,180,0,1,156,0,1.0,1
2,37,1,1,130,283,0,2,98,0,0.0,2
3,48,0,0,138,214,0,1,108,1,1.5,1
4,54,1,2,150,195,0,1,122,0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1
914,68,1,0,144,193,1,1,141,0,3.4,1
915,57,1,0,130,131,0,1,115,1,1.2,1
916,57,0,1,130,236,0,0,174,0,0.0,1
917,38,1,2,138,175,0,1,173,0,0.0,2

In [111]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_scale=sc.fit_transform(x)
x_scale

array([[-1.42815446,  0.515943  ,  0.2245723 , ..., -0.8229452 ,
        -0.85546862,  1.04249607],
       [-0.47585532, -1.93819859,  1.27063705, ..., -0.8229452 ,
         0.13751561, -0.62216462],
       [-1.7455875 ,  0.515943  ,  0.2245723 , ..., -0.8229452 ,
        -0.85546862,  1.04249607],
       ...,
       [ 0.3706328 ,  0.515943  , -0.82149245, ...,  1.21514774,
         0.33611246, -0.62216462],
       [ 0.3706328 , -1.93819859,  0.2245723 , ..., -0.8229452 ,
        -0.85546862, -0.62216462],
       [-1.63977649,  0.515943  ,  1.27063705, ..., -0.8229452 ,
        -0.85546862,  1.04249607]])

In [112]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scale,y,test_size=0.3)

In [113]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

In [114]:
scr_lg=cross_val_score(LogisticRegression(),x_train,y_train,cv=5)
print("LogisticRegression",scr_lg)
print(np.average(scr_lg))
scr_svc=cross_val_score(SVC(),x_train,y_train,cv=5)
print("SVM",scr_svc)
print(np.average(scr_svc))
scr_rf=cross_val_score(RandomForestClassifier(),x_train,y_train,cv=5)
print("Random Forest",scr_rf)
print(np.average(scr_rf))

LogisticRegression [0.83333333 0.86507937 0.84126984 0.79365079 0.784     ]
0.8234666666666668
SVM [0.84126984 0.88888889 0.88888889 0.84126984 0.8       ]
0.8520634920634921
Random Forest [0.82539683 0.85714286 0.88888889 0.81746032 0.792     ]
0.8361777777777777

In [115]:
x_scale.shape

(899, 11)

In [116]:
from sklearn.decomposition import PCA
pca=PCA(0.80)
x_pca=pca.fit_transform(x_scale)
x_pca.shape

(899, 7)

In [117]:
x_train,x_test,y_train,y_test=train_test_split(x_pca,y,test_size=0.3)

In [118]:
scr_rf=cross_val_score(RandomForestClassifier(),x_train,y_train,cv=5)
print("Random Forest",scr_rf)
print(np.average(scr_rf))

Random Forest [0.82539683 0.85714286 0.84920635 0.81746032 0.808     ]
0.8314412698412698